export const ROUTES = {
  ADMIN: {
    DESIGN_HUB: "/admin/design-hub",
    PLAN: "/admin/plan",
    PLAN_SIMPLE_VIEW: "/admin/plan-simple-view",
    PLAN_NEW: "/admin/plan/new",
    CUSTOMER_MANAGEMENT: "/admin/customers",
    CUSTOMER_FORM: "/admin/customer-form",
    LISTINGS: "/admin/listings",
    LISTINGS_DUPLICATE: "/admin/listings/duplicate",
    SOCIAL: "/admin/social",
    SOCIAL_INSIGHTS: "/admin/social-insights",
    PINTEREST: "/admin/pinterest",
    ADS_RECOMMENDATION: "/admin/ads-recommendation",
    STORE_ANALYSIS: "/admin/store-analysis",
    STATS: "/admin/stats",
    ROAS_CALCULATOR: "/admin/roas-calculator",
    ACTIVITY_LOG: "/admin/activity-log",
    PLAN_TASK_RULES: "/admin/plan-task-rules",
    TASKS: "/admin/tasks",
    ROLE_MANAGEMENT: "/admin/role-management",
    SEO: "/admin/seo",
  },
  CUSTOMER: {
    HOME: "/customer/home",
    CUSTOMER: "/customer/customer",
    MEETING_BOOKING: "/customer/meeting-booking",
    MY_INFO: "/customer/my-info",
    PLAN: "/customer/plan",
    LISTINGS: "/customer/listings",
    SOCIAL: "/customer/social",
    DESIGN_HUB: "/customer/design-hub",
    SOCIAL_INSIGHTS: "/customer/social-insights",
    STORE_ANALYSIS: "/customer/store-analysis",
    TAGIFY: "/customer/tagify",
    ROAS_CALCULATOR: "/customer/roas-calculator",
    DESCRIPTION_HERO: "/customer/description-hero",
    ADS_RECOMMENDATION: "/customer/ads-recommendation",
  },
};
