export enum COLLECTIONS {
  admin = "admin",
  customers = "customers",
  feedbackPrompts = "feedbackPrompts",
  images = "images",
  listings = "listings",
  listingOptimizationPrompts = "listingOptimizationPrompts",
  planTaskRules = "planTaskRules",
  plans = "plans",
  socials = "socials",
  stats = "stats",
  storeAnalysis = "storeAnalysis",
  tasklists = "tasklists",
  trafficAnalysis = "trafficAnalysis",
  userActivity = "userActivity",
}
